### ISSUE TITLE
[DEV] Add tftp server to the coredhcp server to seve artifacts

### ISSUE THREAD

**Issue by alexlovelltroy** [OpenCHAMI/coresmd#2]
# Add TFTP Server Capability to coresmd with Optional Command-line Control

### Summary
This issue proposes the addition of a TFTP server within `coresmd`, controlled via a command-line argument. The primary use case is for testing environments and small-scale deployments, where running multiple services can be cumbersome. An integrated TFTP server simplifies setup and management, allowing us to keep DHCP and TFTP services in a single, cohesive package. In addition, embedding the TFTP functionality facilitates our continued development of OpenCHAMI’s bootstrap capabilities, especially as we work with switches supporting Zero Touch Provisioning (ZTP) protocols, such as SONiC’s implementation.

### Rationale
While production-scale deployments will likely require a dedicated TFTP server, having an integrated option within `coresmd` provides key advantages for testing and small setups:
1. **Simplified Configuration**: Managing a single service with both DHCP and TFTP capabilities reduces setup complexity and configuration errors, especially in isolated environments.
2. **Improved Learning and Documentation**: Users can explore and learn how the netboot process works, with DHCP and TFTP artifacts organized within the same repository.
3. **Future Development for ZTP Support**: As OpenCHAMI evolves, having an embedded TFTP server will streamline iteration on ZTP-based features, particularly as we experiment with bootstrap methods on supported switches.

### Proposed Implementation
We suggest using the [`pin/tftp`](https://github.com/pin/tftp) Go package to implement the TFTP server. This would allow `coresmd` to serve files from a specified directory, supporting a variety of netboot workflows.

The TFTP server should be started as a goroutine and controlled by a command-line argument. For example, launching the service with `--enable-tftp` could initiate the TFTP thread with a specified directory (e.g., `--tftp-dir=/path/to/dir`). 

### Example Code
Below is a sample code snippet demonstrating how to integrate a TFTP server using the `pin/tftp` package. This example assumes serving files from a specified directory (`tftpDir`) and listening on a configurable port (`tftpPort`).

```go
package main

import (
    "log"
    "os"
    "github.com/pin/tftp"
)

// startTFTPServer initializes a TFTP server and serves files from the specified directory.
func startTFTPServer(tftpDir string, tftpPort string) {
    // Create new TFTP server for read-only mode
    s := tftp.NewServer(readHandler, nil)
    
    // Configure server to listen on the specified port
    go func() {
        log.Printf("Starting TFTP server on port %s serving directory %s", tftpPort, tftpDir)
        if err := s.ListenAndServe(":" + tftpPort); err != nil {
            log.Fatalf("Failed to start TFTP server: %v", err)
        }
    }()
}

// readHandler defines the logic to serve files for TFTP requests.
func readHandler(filename string, rf io.ReaderFrom) error {
    filepath := path.Join(tftpDir, filename)
    file, err := os.Open(filepath)
    if err != nil {
        log.Printf("Failed to open file: %s", filepath)
        return err
    }
    defer file.Close()

    log.Printf("Serving file: %s", filepath)
    _, err = rf.ReadFrom(file)
    return err
}

func main() {
    tftpDir := "/path/to/tftp/files" // Customize directory for TFTP files
    tftpPort := "69"                  // Default TFTP port, customize as needed

    // Initialize the TFTP server in a separate goroutine
    startTFTPServer(tftpDir, tftpPort)
    
    // Additional service logic for coresmd here...
}
```

### Usage
1. Add a new command-line flag (e.g., `--enable-tftp`) to control TFTP server initialization.
2. Specify the directory to serve TFTP files using another flag (e.g., `--tftp-dir=/path/to/tftp/files`).
3. Optionally, configure the TFTP port with a flag such as `--tftp-port=69`.

### Next Steps
- **Community Feedback**: We welcome feedback on this proposal, particularly from those who might benefit from the integrated TFTP service.
- **Implementation and Testing**: Upon approval, we can proceed with implementing and testing the functionality in a development branch.

This feature aligns with our commitment to making OpenCHAMI more accessible and versatile, especially for those managing network boot processes and ZTP protocols.

**Comment by njones-lanl** [comment]
I think for the deployment recipe we'll want to leave a hanging hint about how we make the pxe file if it's not included in the docker file already.

**Comment by synackd** [comment]
Completed with the merge of #6
